#!/usr/bin/python3

import os
import sys
import py_compile

python_file = os.environ.get("PYFILE")

if not python_file:
    print("Environment variable not set")
    sys.exit(1)

output = f"{python_file}c"

try:
    py_compile.compile(python_file, cfile=output, optimize=-1)
except Exception as e:
    print(f"Compilation failed: {str(e)}")
    sys.exit(1)
